name = "kalo-kalo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION="20.9.0"
AUTH_SECRET="WhASoi+dB9JmevhW4b+aT5+764kQge1vjCSih3LY7fc=" 
FIREBASE_API_KEY="AIzaSyDLa0S6oCWu_WeYOzXKJDs50IYdgb63d2g"
FIREBASE_AUTH_DOMAIN="kalok-3d4d3.firebaseapp.com"
FIREBASE_PROJECT_ID="kalok-3d4d3"
FIREBASE_STORAGE_BUCKET="kalok-3d4d3.appspot.com"
FIREBASE_MESSAGING_SENDER_ID="692801516455"
FIREBASE_APP_ID="1:692801516455:web:f0a86b3e1661dbd76ebc82"
FIREBASE_MEASUREMENT_ID="G-ZDFVDQJDDQ"
MAILERSEND_API_KEY="mlsn.b6013a75d2eac9c6ba2a30fa6f493bcede65924457a1011e9eb8888075dfcee0"
NEXT_PUBLIC_SUPABASE_URL="https://bsgegcfxvgeolqibeogm.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZ2VnY2Z4dmdlb2xxaWJlb2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc0MjE1ODUsImV4cCI6MjA0Mjk5NzU4NX0.WDIHXPjKIOk64R4fLV9H5a2VhId43dKJjVJgLU0H1SA"
SUPABASE_URL="https://bsgegcfxvgeolqibeogm.supabase.co"
SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZ2VnY2Z4dmdlb2xxaWJlb2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc0MjE1ODUsImV4cCI6MjA0Mjk5NzU4NX0.WDIHXPjKIOk64R4fLV9H5a2VhId43dKJjVJgLU0H1SA"
MJ_APIKEY_PUBLIC="f5f51b16e0594cbee42bc851aa9e2ad6"
MJ_APIKEY_PRIVATE="134b1c4134c83902eabf810d3caca73e"