// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  showcase: dynamic(() => import("./Showcase")),
  table: dynamic(() => import("./Table")),
  text_block: dynamic(() => import("./TextBlock")),
};
